# Generated by Django 2.0.4 on 2018-05-11 09:27

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('runner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IoLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=[], size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Preset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(0, 'Started'), (1, 'Finished'), (2, 'Failed')], default=0)),
                ('test_date', models.DateTimeField(auto_now_add=True)),
                ('runner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='runner.Runner')),
            ],
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Testcase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('extra', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='scenario',
            name='testcases',
            field=models.ManyToManyField(through='fio.Job', to='fio.Testcase'),
        ),
        migrations.AddField(
            model_name='result',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fio.Scenario'),
        ),
        migrations.AddField(
            model_name='preset',
            name='scenario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fio.Scenario'),
        ),
        migrations.AddField(
            model_name='job',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fio.Scenario'),
        ),
        migrations.AddField(
            model_name='job',
            name='testcase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fio.Testcase'),
        ),
        migrations.AddField(
            model_name='iolog',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fio.Job'),
        ),
        migrations.AddField(
            model_name='iolog',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='io_logs', to='fio.Result'),
        ),
    ]
